[program:koishi]
directory=/opt/koishi
command=/usr/bin/npm start
environment=NODE_ENV="production"
autostart=true
autorestart=true
startsecs=15
stopasgroup=true
killasgroup=true
stdout_logfile=/var/log/koishi.log
stderr_logfile=/var/log/koishi-error.log
stdout_logfile_maxbytes=10MB
stderr_logfile_maxbytes=10MB
stdout_logfile_backups=7
stderr_logfile_backups=7

